### PR TITLE
added some tests for sparse matrices using wrapper (tests fail).

### PR DESCRIPTION
**Pull request by lruthotto**

### CODE REVIEW

**Comment by lruthotto** [comment]
it's interesting that the tests pass on some platforms. For me the test fails: Here is my setup

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.1-pre+31 (2016-11-17 17:50 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 6a1e339 (109 days old release-0.5)
|__/                   |  x86_64-apple-darwin14.5.0

julia> using ArrayFire
Fontconfig warning: line 146: blank doesn't take any effect anymore. please remove it from your fonts.conf
ArrayFire v3.4.1 (OpenCL, 64-bit Mac OSX, build b9055b1)
[0] APPLE   : GeForce GT 750M, 2048 MB
-1- APPLE   : Iris Pro, 1536 MB
```
and the error: 

```
AFArray: Error showing value of type ArrayFire.AFArray{Float64,2}:
ERROR: ArrayFire Error (202) : Invalid input argument
In function const ArrayInfo &getInfo(const af_array, bool, bool)
In file src/api/c/array.cpp:26
Invalid argument at index 0
Expected: info->isSparse() == false

 in _error(::UInt32) at /Users/lruthot/.julia/v0.5/ArrayFire/src/util.jl:47
 in convert_array(::ArrayFire.AFArray{Float64,2}) at /Users/lruthot/.julia/v0.5/ArrayFire/src/util.jl:130
 in display(::ArrayFire.AFArray{Float64,2}) at /Users/lruthot/.julia/v0.5/ArrayFire/src/util.jl:25
```

**Comment by gaika** [comment]
Tests fail for unrelated reasons (graphics), for you the error is in displaying sparse array (which doesn't seem sparse for some reason). I'll look into it.

**Comment by gaika** [comment]
Also the latest ArrayFire is v3.4.2, not sure if it makes a difference.

**Comment by gaika** [comment]
Yep, it fails to convert sparse AFArray to regular Julia array, otherwise everything is fine. I fixed the display issue by converting it to dense

**Comment by gaika** [comment]
@lruthotto The row / col index for sparse arrays in ArrayFire mean something else, doesn't map to Julia version of `sparse()`. Can you figure it out? Can you add more tests?

**Comment by lruthotto** [comment]
Sure, will add more tests as soon as I have the new version of AF running on my machine. 

Can you clarify how `sparse()` here is different. I noticed a different order of input arguments, but is there more to it? 

Regarding the print: I'm not sure if its a good idea to convert the matrix to dense just to print it. Would that happen on the GPU? If yes, can't we deactivate the printing for now?

**Comment by lruthotto** [comment]
can you guys point me to some more info how to run ArrayFire.jl using the AF version installed through a binary (not through brew)? I'm having trouble running with the latest version. Tried to modify the DYLD_LIBRARY_PATH, but still getting the following error: 

```
julia> using ArrayFire
ERROR: InitError: ArrayFire Error (501) : Failed to load dynamic library.
Error in af_err unified::AFSymbolManager::call(const char *, CalleeArgs...) [CalleeArgs = <>]
In file src/api/unified/symbol_manager.hpp:55
Failed to load dynamic library. See http://www.arrayfire.com/docs/unifiedbackend.htm for instructions to set up environment for Unified backend.

 in _error(::UInt32) at /Users/lruthot/.julia/v0.5/ArrayFire/src/util.jl:47
```

also checked out the website, but didn't really help. sorry for the dumb question but I feel that's needed before I can do more work here.

**Comment by gaika** [comment]
All the tests run with http://ci.arrayfire.org/userContent/OSX/ , have you tried that?

**Comment by gaika** [comment]
Could be GL libraries missing, like in https://github.com/arrayfire/arrayfire/issues/1692

**Comment by lruthotto** [comment]
thanks, this helped. Am operational now again. Will add some more tests later. Dumb question: Should there be a special type for AF sparse matrices? I'm excited to test how fast matvecs are using AF.

**Comment by gaika** [comment]
Maybe a sparse boolean parameter to the type: `AFArray{Type,Dims,Sparse}` ?

**Pull request merged**
